server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  sql:
    init:
      mode: always
      encoding: utf-8
      continue-on-error: true
      data-locations: classpath*:sql/data.sql
      schema-locations: classpath*:sql/schema.sql
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
